### ISSUE TITLE
Duplicate key warning

### ISSUE THREAD

**Issue by andrewwu** [tjwallace/fit#19]
Whenever the library is loaded, [line 685 in definitions.rb](https://github.com/tjwallace/fit/blob/master/lib/fit/file/definitions.rb#L685) shows the following warning:

```
fit-parser-0.0.1/lib/fit/file/definitions.rb:685: warning: 
duplicated key at line 685 ignored: :unit
```

This is caused by that particular line having two `:unit` symbols. Is there a reason why there are two? If not, would it be possible to remove one of them?

**Comment by doc75** [comment]
You are right, this was a mistake during the "automated" conversion from excel.
how did you detect this error ? Any special ruby option turned on ? I have not seen it (currently working with ruby 2.1.6).

**Comment by andrewwu** [comment]
Thanks for the fix!

I have it included in a Rails application and noticed the warning in the development log and Rails console whenever the gem is being included. No special options turned on.
