### ISSUE TITLE
FIT Message 'capabilities' has some odd fields, why?

### ISSUE THREAD

**Issue by karl-petter** [tjwallace/fit#24]
I'm comparing the latest release of the FIT protocol(20.24.01) with the code. At https://github.com/tjwallace/fit/blob/master/lib/fit/file/definitions.rb#L72 is the FIT message called 'capabilities' described. Though when comparing to the description in PDF "D00001309 FIT File Types Description Rev 2.1 .pdf" it shall only have the fields 'languages' and 'workouts_supported' but the code also has 'sports' and 'connectivity_supported'! Are those old leftovers from an older version or why are they there?

**Comment by tjwallace** [comment]
@karl-petter yes, those are most likely from an older version. I think the latest version we have is 1.7, see 8a545ff7ce7cac22f5eed8ff80799b7b81ad6569
