### ISSUE TITLE
Manage invalid values

### ISSUE THREAD

**Issue by doc75** [tjwallace/fit#7]
Current code output the invalid values as if they were real values.
We can imagine 2 options for invalid values:
  1- Output them as blank value i.e empty string (raw value would still return the invalid value)
  2- Output the word 'invalid'

Any advice on the preferred solution before I start to work on this topic ?

**Comment by tjwallace** [comment]
Return `nil`?

**Comment by doc75** [comment]
Yes, you are right. This is so obvious, it's a shame I did not think about this ;-)
